version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./dockerfile
    image: ocl_local_django
    container_name: ocl_django

    volumes:
      - .:/ocl
    ports:
      - "8000:8000"
